# Generated by Django 6.0.3 on 2026-03-25 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='created', verbose_name='Статус')),
                ('priority', models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Приоритетность')),
                ('is_reopened', models.BooleanField(default=False, verbose_name='Переоткрывалась ли')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'tasks',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
