# Generated by Django 6.0.3 on 2026-03-30 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_tasks_assignee_attachments_comments_projects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationTasks',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('task_manager.tasks',),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Приоритетность'),
        ),
    ]
