# Generated by Django 6.0.3 on 2026-04-30 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_educationtasks_alter_tasks_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='attachments', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='message',
            field=models.CharField(max_length=64, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_manager.projects'),
        ),
    ]
