# Generated by Django 6.0.3 on 2026-05-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_attachments_photo_alter_comments_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments', verbose_name='Файл'),
        ),
    ]
